[workspace]
members = ["src/lingcage", "src/lingcore"]
resolver = "3"

[workspace.package]
authors = [
  "LingCage <opensource@lingcage.com>",
  "Ruoqing He <ruoqing.he@lingcage.com>",
]
edition = "2024"
homepage = "https://lingcage.com"
license = "Apache-2.0"
name = "lingcage"
repository = "https://github.com/RuoqingHe/lingcage"
version = "0.1.0"
