version = 1

[[annotations]]
path = [
  # "src/**" should be checked with SPDX headers.
  "**/Cargo.toml",
  "Cargo.lock",
  "rust-toolchain.toml",
  ".rustfmt.toml",
  ".taplo.toml",
  ".mdformat.toml",
  ".typos.toml",
  "REUSE.toml",
  ".gitignore",
  ".github/**",
  "assets/**",
  "**/*.md",
  "**/*.json",
  "LICENSE",
  "LICENSES/**",
]
precedence = "closest"
SPDX-FileCopyrightText = "2026 LingCage <opensource@lingcage.com>"
SPDX-License-Identifier = "Apache-2.0"
