[package]
authors.workspace = true
description = "Building blocks for agentic-workload VMMs."
edition.workspace = true
homepage.workspace = true
license.workspace = true
name = "lingcore"
repository.workspace = true
version.workspace = true

[lints]
workspace = true

[dependencies]
thiserror.workspace = true
