name: LingCage Clippy

on:
  pull_request:

jobs:
  clippy:
    name: Lint With Clippy
    strategy:
      fail-fast: false
      matrix:
        platform:
          - --target x86_64-unknown-linux-gnu
    uses: ./.github/workflows/per-commit.yml
    with:
      run: cargo clippy --workspace --all-targets --locked ${{ matrix.platform }} --features lingcage/agent,lingcore/machine,lingcore/kvm -- -D warnings
